version: '3.1'

services:

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080